### ISSUE TITLE
Light/Control/FuncXX_KeyPress

### ISSUE THREAD

**Issue by TrammRasmusen** [bang-olufsen/bangolufsen-hacs#1]
Hi B&o

It would be nice if this integration could handle the Light and Control/FuncXX_KeyPress, from the Beoremote One.

So it's possible to name the different functions on the remote. 

Thank you for this integration in general - it works flawlessly :)

**Comment by cklit** [comment]
It already does. Use Device triggers in automations, or listen to event: bangolufsen_event

**Comment by cklit** [comment]
![image](https://user-images.githubusercontent.com/23294994/217652585-626b8cea-5d1d-45e8-b5b7-7e2d6f63fb4e.png)

**Comment by cklit** [comment]
![image](https://user-images.githubusercontent.com/23294994/217652698-f14fc134-ea80-4455-8fc0-b1a2be3922bc.png)

**Comment by TrammRasmusen** [comment]
Thank you. I've use the listen function now :)

**Comment by spacecakes** [comment]
> So it's possible to name the different functions on the remote.

It's possible to rename them on the remote, but it's not exactly intuitive. Nothing to do with this integration but here's how: 
add a new product in Settings of the remote, for example a Beovision, select that and go to Settings -> Advanced and you should see customization options for the Control and Light menus. Reorder and rename stuff there and then switch back to the Theatre product and the changes will remain.

Not sure why it's not possible to do this when the Theatre is selected in the remote, but this is a workaround.
