### ISSUE TITLE
Unable to add this integration to HA

### ISSUE THREAD

**Issue by flippair** [bang-olufsen/bangolufsen-hacs#10]
<img width="755" alt="Screenshot 2023-10-26 214326" src="https://github.com/bang-olufsen/bangolufsen-hacs/assets/61556902/4960bb7d-f69d-4da2-973c-fdcc80ab8c7f">

Unable to find this in HACS. Any specific repository needed?

**Comment by mj23000** [comment]
This integration has to be added as a custom repository: https://hacs.xyz/docs/faq/custom_repositories/

**Comment by flippair** [comment]
Got it. Thanks.
