### ISSUE TITLE
Upgrading from 1.5.6 to 1.6.1 bricks the Bang & Olufsen integration

### ISSUE THREAD

**Issue by Jydepotte** [bang-olufsen/bangolufsen-hacs#14]
Downgrading back to 1.5.6 fixes the problem. I am running Home Assistant 2023.9.3.

**Comment by mj23000** [comment]
Do you have any Home Assistant logs that you can share that show the integration failing? And what products do you have added?

Kind regards

**Comment by Jydepotte** [comment]
Hi.... I have just upgraded again... here is the log file. Thank you.

![image](https://github.com/bang-olufsen/bangolufsen-hacs/assets/145715005/941cb725-c251-4718-8744-c326d422b164)

[home-assistant.log](https://github.com/bang-olufsen/bangolufsen-hacs/files/13770936/home-assistant.log)

**Comment by mj23000** [comment]
Thank you. 

The issue was that I added the serial_number device attribute, which was added in HA 2023.11.0, without updating the needed Home Assistant version. I've removed the attribute for now so that you can use the newest version of the integration, which is now 1.6.2, in your current setup.

Kind regards.

**Comment by Jydepotte** [comment]
That did the trick ... thank you for the very quick help.

**Comment by Jydepotte** [comment]
Hej Markus,

Da jeg tilsyneladende er den eneste med problemet (der i hvert fald har meldt det til dig) har jeg sørget for at opdatere min HA installation og du er derfor velkommen til at genindføre din ændring, hvis den har betydning fremadrettet. Jeg tester gerne 😊.

/Jan


Fra: Markus Jacobsen ***@***.***>
Sendt: 8. januar 2024 10:34
Til: bang-olufsen/bangolufsen-hacs ***@***.***>
Cc: Jydepotte ***@***.***>; Author ***@***.***>
Emne: Re: [bang-olufsen/bangolufsen-hacs] Upgrading from 1.5.6 to 1.6.1 bricks the Bang & Olufsen integration (Issue #14)

Du får ikke ofte mails fra ***@***.******@***.***>. Få mere at vide om, hvorfor dette er vigtigt<https://aka.ms/LearnAboutSenderIdentification>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Closed #14<https://github.com/bang-olufsen/bangolufsen-hacs/issues/14> as completed.
