### ISSUE TITLE
Did 1.7 just break my lights?

### ISSUE THREAD

**Issue by FrankLundgreen** [bang-olufsen/bangolufsen-hacs#15]
Hi

Did 1.7 break my lights which I control from my beoremote. The trace reports an error:
"UndefinedError: 'dict object' has no attribute 'event'"

see full trace here:

[trace automation.beoremote_lys 2024-01-18T17_31_44.161231+00_00.json](https://github.com/bang-olufsen/bangolufsen-hacs/files/13980223/trace.automation.beoremote_lys.2024-01-18T17_31_44.161231%2B00_00.json)

Kind regards
Frank

**Comment by mj23000** [comment]
It looks like there are some problems with 1.7.0, so I've decided to pull it for now. Please revert to 1.6.2 for the time being.

Kind regards.
