### ISSUE TITLE
Music Assistant support

### ISSUE THREAD

**Issue by spacecakes** [bang-olufsen/bangolufsen-hacs#2]
I've been trying to get my Theatre playing though [Music Assistant](https://github.com/music-assistant/hass-music-assistant), but it doesn't work. It seems like it won't play the stream and instead just continues playing whatever was playing previously as set by another app. I.e. play/pause works, but setting the content stream does not. 

I've followed [the troubleshooting advice](https://github.com/music-assistant/hass-music-assistant/discussions/622) of Music Assistant but alas it didn't help.

Theoretically it should work, according to the developers. Just wondering if anyone's tried this successfully combination successfully and what you had to do to get streams working. 

_Thanks a lot for this integration. I use it all the time, every day. It's been a game changer._

**Comment by mj23000** [comment]
There was an oversight in the play_media method which has been fixed in version 0.6.3. I could get a Beosound Balance to play Youtube Music so hopefully it will work for your setup. 

Glad you're enjoying the integration and thanks for the bug report.

**Comment by spacecakes** [comment]
Can confirm this now works flawlessly (as far as I can tell from the first 15 minutes). Thanks a lot!
