### ISSUE TITLE
Can't add second integration (new A5)

### ISSUE THREAD

**Issue by elcriuz** [bang-olufsen/bangolufsen-hacs#4]
I am trying to add my new Beosound A5 to my existing Beosound Balance, but when I enter IP and device model correctly I only get this: 
<img width="431" alt="CleanShot 2023-05-28 at 12 09 07@2x" src="https://github.com/bang-olufsen/bangolufsen-hacs/assets/98161879/3738b578-fcf5-4854-98f1-4d7b1111261d">

**Comment by elcriuz** [comment]
How can I log this? Sorry!

**Comment by mj23000** [comment]
Settings->System->Logs->Load full logs. There should be some warning or error messages from the bangolufsen integration. You may need to try to add the Beosound A5 again for these to appear.
