### ISSUE TITLE
An error occurred while initializing the device. Try waiting or restarting the device.

### ISSUE THREAD

**Issue by Rasm6162** [bang-olufsen/bangolufsen-hacs#6]
Hi
I have tried multiple ways to connect my A9, but I keep running into this error:
_An error occurred while initializing the device. Try waiting or restarting the device._

in the log I get some errors like:

ERROR (MainThread) [frontend.js.latest.202308020] :0:0 Script error.

WARNING (Thread-10 (worker)) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6d6e2490>: Failed to establish a new connection: [Errno 111] Connection refused')': /api/v1/beolink/self

Shall I open anything in the Beoplay app?
Can I add the speaker though a config file? 

Thanks

**Comment by cklit** [comment]
Can you confirm that it is a Beosound A9 5th Gen? (And not Beoplay A9 1-4th gen)

**Comment by Rasm6162** [comment]
Sorry you are right mine is a Gen4.. wasn't aware of the new release. 👍
