### ISSUE TITLE
Events stop firing

### ISSUE THREAD

**Issue by spacecakes** [bang-olufsen/bangolufsen-hacs#9]
I've noticed with increased frequency that sometimes when I pick up the remote and try to control something, the automation does not trigger. This is because the `bangolufsen_event` is no longer firing, as verified by adding a listener to it in the HA developer tools. Reloading the integration always fixes it, but is cumbersome. 

Interestingly, everything else about the integration seems to work as normal when this happens. I can still control my product within HA—it's just the events from the remote that stop working. 

Have you seen this behavior and do you have any idea what causes it and how it can be fixed?

Thank you

**Comment by spacecakes** [comment]
I enabled debug logging over night and it has been spamming the console with `listener thread` debug output all night, but  at around 6:46 this morning it stopped completely. I wonder if that's when events stopped working too. 

Example with fudged serial number:
```
2023-10-12 06:46:43.472 DEBUG (10.0.1.23 - listener thread) [custom_components.bangolufsen.coordinator] {'eventData': {'secondsRemaining': 0, 'value': 'noUpdatesAvailable'}, 'eventType': 'WebSocketEventSoftwareUpdateState', 'device_id': '96d7e7ea12d8d09ff7b2b6627e0089d7', 'serial_number': 36194825}

**Comment by mj23000** [comment]
My remote was not triggering WebSocket events either and reloading the integration did not fix the problem for me. This was fixed by unpairing and pairing the remote again. Now remote control WebSocket events and by proxy bangolufsen_events are sent again, but I haven't done any long term tests yet. 

This looks like Mozart platform bug more than an API or HA integration bug. I will be monitoring the situation.

**Comment by spacecakes** [comment]
Thanks for confirming! I've noticed that it has continued working the last few days without me changing anything. Not sure what's going on but I agree it looks like a Mozart bug. Although restarting the integration fixed it, which lead me to suspect the integration at first

**Comment by spacecakes** [comment]
I haven't had this occur in two months now for whatever reason, so closing
